version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/geo-search"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "github actions"
      - "dependencies"
    schedule:
      interval: "daily"
