version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "github actions"
      - "dependencies"
    schedule:
      interval: "daily"
