version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/geo-search"
    labels:
      - "dependencies"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "github actions"
      - "dependencies"
    schedule:
      interval: "daily"
