[build]
  base = "geo-search/"
  publish = "dist/geo-search"
  command = "yarn run build"

[dev]
  command = "yarn run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/geo-search/*"
  to = "/geo-search/:splat"
  status = 200
  force = true
