github.com:
    users:
        oc-2:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: oc-2
