github.com:
    users:
        oc-2:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: oc-2
