compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@angular/compiler-cli@*":
    dependencies:
      "@angular/compiler": "*"
  "@angular/common@*":
    dependencies:
      "@angular/core": "*"
  "@angular/core@*":
    dependencies:
      zone.js: "*"
  "@angular/platform-browser-dynamic@*":
    dependencies:
      "@angular/core": "*"
      "@angular/common": "*"
  "@angular/platform-browser@*":
    dependencies:
      "@angular/core": "*"
      "@angular/common": "*"
  "@angular/router@*":
    dependencies:
      "@angular/core": "*"
      "@angular/common": "*"
  "@angular/ssr@*":
    dependencies:
      beasties: "*"
  "@types/express@*":
    dependencies:
      serve-static: "*"
      body-parser: "*"
  "@types/node@*":
    dependencies:
      events: "*"
      buffer: "*"
      punycode: "*"
      string_decoder: "*"
  "@angular/*@*":
    dependencies:
      tslib: "*"